AWSTemplateFormatVersion: '2010-09-09'

Description: Deploys the prerequisites for the webapp Pipeline to function. The deployed CodeBuild project must be run before deploying the full webapp template.

Parameters:

  CodeCommitName:
    Type: String
    Default: deepracer-event-webapp

Conditions:

  InitialBuild: !Not [!Equals [!Ref CodeCommitName, '']]

Resources:

  ECRRepository:
    Type: AWS::ECR::Repository

  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/codebuild/deepracer-event-webapp-initialbuild
      RetentionInDays: 7

  CodeBuildRole:
    Condition: InitialBuild
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: codebuild
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRRepository}'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !GetAtt CodeBuildLogGroup.Arn
              - Effect: Allow
                Action:
                  - codecommit:GitPull
                Resource: !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitName}'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: IAM does not allow resource level policy for these actions.

  CodeBuildProject:
    Condition: InitialBuild
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODECOMMIT
        Location: !Sub https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${CodeCommitName}
        BuildSpec: flask-app/buildspec_ecr_only.yml
      Artifacts:
        Type: NO_ARTIFACTS
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref CodeBuildLogGroup
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: IMAGE_TAG
            Type: PLAINTEXT
            Value: latest
          - Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref ECRRepository
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W32
            reason: Deliberately choosing to use the default encryption key.

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:

  ECRRepository:
    Value: !Ref ECRRepository
    Export:
      Name: deepracer-event-ECRRepository

  CloudFormationRole:
    Value: !GetAtt CloudFormationRole.Arn
    Export:
      Name: deepracer-event-CloudFormationRole

  CodeBuildProject:
    Value: !If [InitialBuild, !Ref CodeBuildProject, '']
