AWSTemplateFormatVersion: '2010-09-09'

Description: An IAM Role to allow Deep Racer event team to collect Deep Racer Models cross account.

Resources:

  DeepRacerRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role that the Deep Racer Model Uploader will assume.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: '{{ EventAccountId }}'
      Policies:
        - PolicyName: Access-DeepRacer-Models
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:ListAllMyBuckets'
                Resource: '*'
              - Effect: Allow
                Action: 's3:ListBucket'
                Resource: 'arn:aws:s3:::aws-deepracer-*'
              - Effect: Allow
                Action: 's3:GetObject'
                Resource: 'arn:aws:s3:::aws-deepracer-*/*'
              - Effect: Allow
                Action: 'sagemaker:DescribeTrainingJob'
                Resource: !Sub 'arn:aws:sagemaker:us-east-1:${AWS::AccountId}:training-job/dr-sm-rltj*'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: s3:ListAllMyBuckets required for all buckets